### ISSUE TITLE
Docking/tab support

### ISSUE THREAD

**Issue by VelocityRa** [adobe/imgui#6]
There are docking branches on this repo, but docking/tabs are not supported - their style is not changed or consistent with Spectrum at all.

**Comment by HasKha** [comment]
Replying to old issue, but I hope this is helpful.

I improved the default display of tabs, but they are not the same as in Spectrum. The way imgui handles it makes it difficult to really match.

Given that style and docking are planned to be re-written, I am not planning to spend time on the current version, it works well enough as it is.
